### ISSUE TITLE
The system is not yet ready to accept queries error message

### ISSUE THREAD

**Issue by aleksei-oecd** [Vettabase/mariadb-columnstore-docker#21]
Using locally build docker from the `main` branch and after running simple select query I get following message:

```
the system is not yet ready to accept queries
	at org.mariadb.jdbc.export.ExceptionFactory.createException(ExceptionFactory.java:297)
	at org.mariadb.jdbc.export.ExceptionFactory.create(ExceptionFactory.java:368)
	at org.mariadb.jdbc.message.ClientMessage.readPacket(ClientMessage.java:137)
	at org.mariadb.jdbc.client.impl.StandardClient.readPacket(StandardClient.java:833)
	at org.mariadb.jdbc.client.impl.StandardClient.readResults(StandardClient.java:772)
	at org.mariadb.jdbc.client.impl.StandardClient.readResponse(StandardClient.java:691)
	at org.mariadb.jdbc.client.impl.StandardClient.execute(StandardClient.java:634)
	at org.mariadb.jdbc.Statement.executeInternal(Statement.java:935)
	at org.mariadb.jdbc.Statement.execute(Statement.java:1061)
	at org.mariadb.jdbc.Statement.execute(Statement.java:452)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.execute(JDBCStatementImpl.java:330)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.executeStatement(JDBCStatementImpl.java:131)
```

The sample table

```
CREATE TABLE `sample_data` (
  `id` int(11) DEFAULT NULL,
  `first_name` varchar(50) DEFAULT NULL,
  `last_name` varchar(50) DEFAULT NULL,
  `email` varchar(50) DEFAULT NULL,
  `gender` varchar(50) DEFAULT NULL,
  `ip_address` varchar(20) DEFAULT NULL
) ENGINE=ColumnStore 
```

Insert:

```
INSERT INTO `sample_data` VALUES(1,'Hillery','Rizzillo','hrizzillo0@ezinearticles.com','Male','250.79.234.200');
```

Select after which i get before mentioned error:

```
select * from `sample_data`;
```

**Comment by rcbensley** [comment]
Hi, thanks I shall test this myself.

**Comment by rcbensley** [comment]
I can easily recreate the error.
I have yet to make any progress on this to produce any meaningful output from the processes which need to run. I have opened #22, to handle the evalaution and eventualy migration to something liek systemd in docker. It's clunky, but there are too many scripts which need porting.
